<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create([
            'emp' => "admin",
            'email' => "admin@admin.com",
            'password' => Hash::make("111"),
            'nombre' => "admin",
            'apellido_paterno' => "admin",
            'apellido_materno' => "admin",
            'user_type_id' => 1,
            'user_title_id' => 1,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "3379",
            'email' => "bruno.gomes@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Bruno",
            'apellido_paterno' => "Lorena",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3996",
            'email' => "ricardo.costa@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Ricardo",
            'apellido_paterno' => "Costa",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4029",
            'email' => "teogenes.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Teogenes",
            'apellido_paterno' => "Lima",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3900",
            'email' => "josias.campgnoli@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Josias",
            'apellido_paterno' => "Campgnoli",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3955",
            'email' => "leonardo.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Leonardo",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3457",
            'email' => "dalmer.vieira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Dalmer",
            'apellido_paterno' => "Vieira",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3461",
            'email' => "andre.alves@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "André",
            'apellido_paterno' => "Alves",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3428",
            'email' => "marcelo.serres@gi-de.com ",
            'password' => Hash::make("111"),
            'nombre' =>  "Marcelo",
            'apellido_paterno' => "Serres",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3824",
            'email' => "marcus.oliveira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Marcus",
            'apellido_paterno' => "Oliveira",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3763",
            'email' => "luiz.godoy@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Luiz",
            'apellido_paterno' => "Godoy",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3821",
            'email' => "edinelson.cunha@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Edinelson",
            'apellido_paterno' => "Cunha",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4078",
            'email' => "raphael.modanez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Raphael",
            'apellido_paterno' => "Modanez",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3972",
            'email' => "joao.junior@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "João",
            'apellido_paterno' => "Júnior",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3904",
            'email' => "jeferson.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Jeferson",
            'apellido_paterno' => "Santos",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4017",
            'email' => "alexandre.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Alexandre",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3626",
            'email' => "marcos.martins@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Marcos",
            'apellido_paterno' => "Martins",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3691",
            'email' => "felipe.braga@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Felipe",
            'apellido_paterno' => "Braga",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3898",
            'email' => "gelson.santana@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Gelson",
            'apellido_paterno' => "Santana",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3568",
            'email' => "cassio.frota@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Cássio",
            'apellido_paterno' => "dos Anjos Frota",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4073",
            'email' => "adriano.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Adriano",
            'apellido_paterno' => "Lima",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3797",
            'email' => "thales.goncalves@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Thales",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3535",
            'email' => "fabiano.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Fabiano",
            'apellido_paterno' => "Santos",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3552",
            'email' => "elton.pereira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Elton",
            'apellido_paterno' => "Pereira",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3594",
            'email' => "felipe.rossetto@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Felipe",
            'apellido_paterno' => "Rossetto",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3460",
            'email' => "aidan.brito@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Aidan",
            'apellido_paterno' => "Brito",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3713",
            'email' => "amauri.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Amauri",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3382",
            'email' => "dhiogo.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Dhiogo",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3554",
            'email' => "breno.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Breno",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3556",
            'email' => "eliton.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Eliton",
            'apellido_paterno' => "Santos",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3881",
            'email' => "jose.teixeira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "José",
            'apellido_paterno' => "Teixeira",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3553",
            'email' => "edinor.junior@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Edinor",
            'apellido_paterno' => "Junior",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3989",
            'email' => "tiago.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Tiago",
            'apellido_paterno' => "Filipe da Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4016",
            'email' => "anderson.martins@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Anderson",
            'apellido_paterno' => "Martins",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3935",
            'email' => "sergio.dasilva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Sérgio",
            'apellido_paterno' => "da Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4038",
            'email' => "armando.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Armando",
            'apellido_paterno' => "Lima",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4059",
            'email' => "paulo.barros@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Paulo",
            'apellido_paterno' => "Barros",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3778",
            'email' => "nilson.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Nilson",
            'apellido_paterno' => "Lima",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3901",
            'email' => "lincoln.delima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Lincoln",
            'apellido_paterno' => "de Lima",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3323",
            'email' => "diego.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Diego",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3313",
            'email' => "daniel.marinho@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Daniel",
            'apellido_paterno' => "Marinho",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3822",
            'email' => "wallace.barbosa@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Wallace",
            'apellido_paterno' => "Barbosa",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3199",
            'email' => "alexandre.nascimento@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Alexandre",
            'apellido_paterno' => "Nascimento",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3003",
            'email' => "fabio.decker@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Fabio",
            'apellido_paterno' => "Decker",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3016",
            'email' => "antonio.sumida@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Antonio",
            'apellido_paterno' => "Sumida",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3732",
            'email' => "flavio.ramos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Flávio",
            'apellido_paterno' => "Ramos",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3254",
            'email' => "milton.mello@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Milton",
            'apellido_paterno' => "Mello",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 10,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "2039",
            'email' => "carlos.torres@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Carlos",
            'apellido_paterno' => "Torres",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 4,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "3873",
            'email' => "leandro.sanchez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Leandro",
            'apellido_paterno' => "Sanchez",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 9,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4048",
            'email' => "rafael.vianna@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Rafael",
            'apellido_paterno' => "Vianna",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 9,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4006",
            'email' => "grabriel.belizario@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Gabriel",
            'apellido_paterno' => "Belizario",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4062",
            'email' => "andre.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Andre",
            'apellido_paterno' => "Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);
        User::create([
            'emp' => "4070",
            'email' => "fabio.dasilva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Fabio",
            'apellido_paterno' => "da Silva",
            'apellido_materno' => NULL,
            'user_type_id' => 2,
            'user_title_id' => 3,
            'country_id' => 1,
        ]);

        User::create([
            'emp' => "E03814",
            'email' => "cesaralberto.antoniogomez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Cesar Alberto",
            'apellido_paterno' => "Antonio",
            'apellido_materno' => "Gómez",
            'telefono' => "55 4449 4655",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E02768",
            'email' => "miguel.castro@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Miguel",
            'apellido_paterno' => "Castro",
            'apellido_materno' => "Peralta",
            'telefono' => "55 5402 2178",
            'user_type_id' => 2,
            'user_title_id' => 5,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E04015",
            'email' => "stefhany.estebanraygoza@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Stefhany",
            'apellido_paterno' => "Esteban",
            'apellido_materno' => "Raygoza",
            'telefono' => "56 5113 9800",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E04020",
            'email' => "estebanfernando.felixanaya@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Esteban Fernando",
            'apellido_paterno' => "Felix",
            'apellido_materno' => "Anaya",
            'telefono' => "55 4370 0853",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03735",
            'email' => "misael.galindomora@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Misael",
            'apellido_paterno' => "Galindo",
            'apellido_materno' => "Mora",
            'telefono' => "55 4144 9867",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03868",
            'email' => "alexander.galvezcruz@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Alexander",
            'apellido_paterno' => "Galvez",
            'apellido_materno' => "Pérez",
            'telefono' => "56 2559 5739",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03812",
            'email' => "jonathan.gutierrezsanchez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Jonathan",
            'apellido_paterno' => "Gutierrez",
            'apellido_materno' => "Sánchez",
            'telefono' => "55 4449 6132",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03811",
            'email' => "rodrigoaurelio.ibarramartinez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Rodrigo Aurelio",
            'apellido_paterno' => "Ibarra",
            'apellido_materno' => "Martínez",
            'telefono' => "55 4449 7347",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03830",
            'email' => "epifanio.jimenezperalta@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Epifanio",
            'apellido_paterno' => "Jimenez",
            'apellido_materno' => "Peralta",
            'telefono' => "55 4523 4278",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03869",
            'email' => "eduardo.juarezperez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Eduardo",
            'apellido_paterno' => "Juárez",
            'apellido_materno' => "Pérez",
            'telefono' => "56 2559 6431",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03587",
            'email' => "hector.lugo@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Héctor",
            'apellido_paterno' => "Lugo",
            'apellido_materno' => "Orozco",
            'telefono' => "55 8096 7915",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03728",
            'email' => "gamaliel.lunajaimes@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Gamaliel",
            'apellido_paterno' => "Luna",
            'apellido_materno' => "Jaimes",
            'telefono' => "55 3479 2737",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03540",
            'email' => "josue.martinez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Josue",
            'apellido_paterno' => "Martinez",
            'apellido_materno' => "Jiménez",
            'telefono' => "55 7909 6010",
            'user_type_id' => 2,
            'user_title_id' => 8,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03825",
            'email' => "victormanuel.mendozaramirez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Victor Manuel",
            'apellido_paterno' => "Mendoza",
            'apellido_materno' => "Ramírez",
            'telefono' => "56 2558 7144",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03888",
            'email' => "christiandavid.palaciosrojas@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Christian David",
            'apellido_paterno' => "Palacios",
            'apellido_materno' => "Rojas",
            'telefono' => "56 2559 6433",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03889",
            'email' => "alvaro.perezperez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Alvaro",
            'apellido_paterno' => "Pérez",
            'apellido_materno' => "Pérez",
            'telefono' => "56 2559 6427",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03899",
            'email' => "rafale.portillagonzalez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Rafael",
            'apellido_paterno' => "Portilla",
            'apellido_materno' => "González",
            'telefono' => "56 2559 6432",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E04014",
            'email' => "carlosmakley.pulidoruiz@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Carlos Makley",
            'apellido_paterno' => "Pulido",
            'apellido_materno' => "Ruiz",
            'telefono' => "56 5112 8143",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03900",
            'email' => "jairomisrraim.reyesmendoza@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Jairo Misrraim",
            'apellido_paterno' => "Reyes",
            'apellido_materno' => "Mendoza",
            'telefono' => "56 2559 6428",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03930",
            'email' => "oscaralberto.riosmartinez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Oscar Alberto",
            'apellido_paterno' => "Rios",
            'apellido_materno' => "Martínez",
            'telefono' => "55 4484 1603",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03829",
            'email' => "josue.roblesmonroy@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Josue",
            'apellido_paterno' => "Robles",
            'apellido_materno' => "Monroy",
            'telefono' => "56 1998 8574",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03465",
            'email' => "said.salinas@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Said",
            'apellido_paterno' => "Salinas",
            'apellido_materno' => "Chávez",
            'telefono' => "55 4356 5100",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03545",
            'email' => "gabriel.santosmartinez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Gabriel",
            'apellido_paterno' => "Santos",
            'apellido_materno' => "Martinez",
            'telefono' => "55 7909 6011",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03733",
            'email' => "marcosjorge.vazquezquiroz@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Marcos Jorge",
            'apellido_paterno' => "Vazquez",
            'apellido_materno' => "Quiroz",
            'telefono' => "55 7928 4899",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03606",
            'email' => "victor.velasco@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Victor Hugo",
            'apellido_paterno' => "Velasco",
            'apellido_materno' => "Carrillo",
            'telefono' => "55 8095 0285",
            'user_type_id' => 2,
            'user_title_id' => 8,
            'country_id' => 2,
        ]);
        User::create([
            'emp' => "E03015",
            'email' => "ernesto.zaldivar@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' =>  "Ernesto",
            'apellido_paterno' => "Zaldivar",
            'apellido_materno' => "Muñoz",
            'telefono' => "55 4554 9345",
            'user_type_id' => 2,
            'user_title_id' => 2,
            'country_id' => 2,
        ]);



    }
}
