<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::create(['emp' => "3379",
            'email' => "bruno.gomes@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Bruno Lorena",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3996",
            'email' => "ricardo.costa@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Ricardo Costa",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4029",
            'email' => "teogenes.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Teogenes Lima",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3900",
            'email' => "josias.campgnoli@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Josias Campgnoli",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3955",
            'email' => "leonardo.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Leonardo Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3457",
            'email' => "dalmer.vieira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Dalmer Vieira",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3461",
            'email' => "andre.alves@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "André Alves",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3428",
            'email' => "marcelo.serres@gi-de.com ",
            'password' => Hash::make("111"),
            'nombre' => "Marcelo Serres",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3824",
            'email' => "marcus.oliveira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Marcus Oliveira",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3763",
            'email' => "luiz.godoy@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Luiz Godoy",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3821",
            'email' => "edinelson.cunha@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Edinelson Cunha",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4078",
            'email' => "raphael.modanez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Raphael Modanez",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3972",
            'email' => "joao.junior@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "João Júnior",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3904",
            'email' => "jeferson.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Jeferson Santos",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4017",
            'email' => "alexandre.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Alexandre Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3626",
            'email' => "marcos.martins@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Marcos Martins",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3691",
            'email' => "felipe.braga@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Felipe Braga",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3898",
            'email' => "gelson.santana@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Gelson Santana",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3568",
            'email' => "cassio.frota@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Cássio dos Anjos Frota",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4073",
            'email' => "adriano.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Adriano Lima",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3797",
            'email' => "thales.goncalves@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Thales Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3535",
            'email' => "fabiano.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Fabiano Santos",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3552",
            'email' => "elton.pereira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Elton Pereira",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3594",
            'email' => "felipe.rossetto@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Felipe Rossetto",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3460",
            'email' => "aidan.brito@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Aidan Brito",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3713",
            'email' => "amauri.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Amauri Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3382",
            'email' => "dhiogo.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Dhiogo Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3554",
            'email' => "breno.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Breno Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3556",
            'email' => "eliton.santos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Eliton Santos",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3881",
            'email' => "jose.teixeira@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "José Teixeira",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3553",
            'email' => "edinor.junior@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Edinor Junior",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3989",
            'email' => "tiago.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Tiago Filipe da Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4016",
            'email' => "anderson.martins@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Anderson Martins",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3935",
            'email' => "sergio.dasilva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Sérgio da Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4038",
            'email' => "armando.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Armando Lima",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4059",
            'email' => "paulo.barros@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Paulo Barros",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3778",
            'email' => "nilson.lima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Nilson Lima",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3901",
            'email' => "lincoln.delima@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Lincoln de Lima",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3323",
            'email' => "diego.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Diego Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3313",
            'email' => "daniel.marinho@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Daniel Marinho",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3822",
            'email' => "wallace.barbosa@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Wallace Barbosa",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3199",
            'email' => "alexandre.nascimento@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Alexandre Nascimento",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3003",
            'email' => "fabio.decker@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Fabio Decker",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3016",
            'email' => "antonio.sumida@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Antonio Sumida",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3732",
            'email' => "flavio.ramos@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Flávio Ramos",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3254",
            'email' => "milton.mello@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Milton Mello",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "2039",
            'email' => "carlos.torres@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Carlos Torres",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "3873",
            'email' => "leandro.sanchez@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Leandro Sanchez",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4048",
            'email' => "rafael.vianna@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Rafael Vianna",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4006",
            'email' => "grabriel.belizario@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Gabriel Belizario",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4062",
            'email' => "andre.silva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Andre Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);
User::create(['emp' => "4070",
            'email' => "fabio.dasilva@gi-de.com",
            'password' => Hash::make("111"),
            'nombre' => "Fabio da Silva",
            'apellido_paterno' => "Pendiente",
            'apellido_materno' => "Pendiente",
            'user_type_id' => 2,
            'user_title_id' => 1,
        ]);

    }
}
